version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "isbn-scanner"
s3_bucket = ""         # SAM will create one, or set your own
s3_prefix = "isbn-scanner"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod"
